apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cc-frontend
data:
  default.conf: |
    server {
      listen 80;

      location / {
        proxy_pass http://check-tomcat-svc.cc-backend.svc.cluster.local:8080;
      }
    }
